# This Script Explores the Tensorflow Library


In [7]:
#importing tensorflow

import tensorflow as tf

# Initialize two constants
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

# Multiply
result = tf.multiply(x1, x2)

# Print the result (returned element wise multiplication between both x1/x2 array vars
print(result)

tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)


In [8]:
#pladeholders = the tensorflow equivalent of a none
#pladeholders will reference tensors later in our program
#variables = tensorflow variables that can change their value
#constants = tensorflow  variables that can NOT change their value

#using a session to actually get tf to calculate our result


# Construct a "Session" to execute the computation graph.
with tf.compat.v1.Session() as sess:
    # Initialize two constants
    x1 = tf.constant([[1,2,3,4],[5,6,7,8]])
    x2 = tf.constant([[9,10,11,12],[13,14,15,16]])
    result = tf.multiply(x1, x2)
    result = sess.run(result)
    print(result)


[[  9  20  33  48]
 [ 65  84 105 128]]
